EJERCICIO 3. Se desea modelizar el conocimiento de la tabla periódica. A través del conocimiento del símbolo del elemento, el estado del elemento, el número periódico del elemento.
Se pide:
Construir la base de reglas que modelice dichos conocimientos para identificar el nombre del elemento.

elemento(actinio,ac,89).
elemento(aluminio,al,13).
elemento(americio,am,95).
elemento(antimonio,sb,51).
elemento(argón,ar,18).
elemento(arsénico,as,33).
elemento(astato,at,85).
elemento(azufre,s,16).
elemento(bario,ba,56).
elemento(berilio,be,4).
elemento(berkelio,bk,97).
elemento(bismuto,bi,83).
elemento(bohrio,bh,107).
elemento(boro,b,5).
elemento(bromo,br,35).
elemento(cadmio,cd,48).
elemento(calcio,ca,20).
elemento(californio,cf,98).
elemento(carbono,c,6).
elemento(cerio,ce,58).
elemento(cesio,cs,55).
elemento(circonio,zr,40).
elemento(cloro,cl,17).
elemento(cobalto,co,27).
elemento(cobre,cu,29).
elemento(copernicio,cn,112).
elemento(cromo,cr,24).
elemento(curio,cm,96).
elemento(darmstatio,ds,110).
elemento(disprosio,dy,66).
elemento(dubnio,db,105).
elemento(einstenio,es,99).
elemento(erbio,er,68).
elemento(escandio,sc,21).
elemento(estaño,sn,50).
elemento(estroncio,sr,38).
elemento(europio,eu,63).
elemento(fermio,fm,100).
elemento(flerovio,fl,114).
elemento(flúor,f,9).
elemento(fósforo,p,15).
elemento(francio,fr,87).
elemento(gadolinio,gd,64).
elemento(galio,ga,31).
elemento(germanio,ge,32).
elemento(hafnio,hf,72).
elemento(hasio,hs,108).
elemento(helio,he,2).
elemento(hidrógeno,h,1).
elemento(hierro,fe,26).
elemento(holmio,ho,67).
elemento(indio,in,49).
elemento(iridio,ir,77).
elemento(iterbio,yb,70).
elemento(itrio,y,39).
elemento(kriptón,kr,36).
elemento(lantano,la,57).
elemento(lawrencio,lr,103).
elemento(litio,li,3).
elemento(livermorio,lv,116).
elemento(lutecio,lu,71).
elemento(magnesio,mg,12).
elemento(manganeso,mn,25).
elemento(meitnerio,mt,109).
elemento(mendelevio,md,101).
elemento(mercurio,hg,80).
elemento(molibdeno,mo,42).
elemento(moscovio,mc,115).
elemento(neodimio,nd,60).
elemento(neón,ne,10).
elemento(neptunio,np,93).
elemento(nihonio,nh,113).
elemento(niobio,nb,41).
elemento(niquel,ni,28).
elemento(nitrógeno,n,7).
elemento(nobelio,no,102).
elemento(oganessón,og,118).
elemento(oro,au,79).
elemento(osmio,os,76).
elemento(oxígeno,o,8).
elemento(paladio,pd,46).
elemento(plata,ag,47).
elemento(platino,pt,78).
elemento(plomo,pb,82).
elemento(plutonio,pu,94).
elemento(polonio,po,84).
elemento(potasio,k,19).
elemento(praseodimio,pr,59).
elemento(prometio,pm,61).
elemento(protactinio,pa,91).
elemento(radio,ra,88).
elemento(radón,rn,86).
elemento(renio,re,75).
elemento(rodio,rh,45).
elemento(roentgenio,rg,111).
elemento(rubidio,rb,37).
elemento(rutenio,ru,44).
elemento(rutherfordio,rf,104).
elemento(samario,sm,62).
elemento(seaborgio,sg,106).
elemento(selenio,se,34).
elemento(silicio,si,14).
elemento(sodio,na,11).
elemento(talio,tl,81).
elemento(tántalo,ta,73).
elemento(tecnecio,tc,43).
elemento(telurio,te,52).
elemento(teneso,ts,117).
elemento(terbio,tb,65).
elemento(titanio,ti,22).
elemento(torio,th,90).
elemento(tulio,tm,69).
elemento(uranio,u,92).
elemento(vanadio,v,23).
elemento(wolframio,w,74).
elemento(xenón,xe,54).
elemento(yodo,i,53).

elementoPeriodico(Nombre, Simbolo, Numero):-elemento(Nombre, Simbolo, Numero).
